### PR TITLE
💀 Fix Footer Responsiveness!

### PR DESCRIPTION
**Pull request by ArnavK-09**
Screenshot_2023-11-20-22-03-49-06_4d38fce200f96aeac5e860e739312e76

### CODE REVIEW

**Comment by ArnavK-09** [comment]
@arunavabasu-03 👋

**Comment by ArnavK-09** [comment]
@arunavabasu-03 👋

# Merge it 🐐

**Comment by ArnavK-09** [comment]
# 💀

**Comment by ArnavK-09** [comment]
@arunavabasu-03

**Comment by arunavabasucom** [comment]
great @ArnavK-09 !

**Pull request merged**
